import { LiteGraphStatic } from './LiteGraph';
import { LGraph } from './LGraph';
import { LGraphNode } from './LGraphNode';
import { LGraphGroup } from './LGraphGroup';
import { ContextMenu } from './ContextMenu';

export interface CanvasOptions {
    skip_render?: boolean;
    skip_events?: boolean;
    autoresize?: boolean;
}

export interface LinkRenderInfo {
    from: number[];
    to: number[];
    color?: string;
}

/**
 * LGraphCanvas - Renders a graph using Canvas2D
 */
export class LGraphCanvas {
    static LiteGraph: LiteGraphStatic;
    static LGraph: typeof LGraph;
    static LGraphNode: typeof LGraphNode;
    static LGraphGroup: typeof LGraphGroup;
    static ContextMenu: typeof ContextMenu;
    static DEFAULT_BACKGROUND_IMAGE: string;
    static link_type_colors: Record<string, string>;
    static node_colors: Record<string, { color: string, bgcolor: string, groupcolor: string }>;
    static gradients: Record<string, CanvasGradient>;
    static search_limit: number;
    static getFileExtension(url: string): string;
    static decodeHTML(str: string): string;
    static setLiteGraph(lg: LiteGraphStatic): void;

    // Instance properties
    graph: LGraph | null;
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    ds: any; // DragAndScale
    max_zoom: number;
    min_zoom: number;
    zoom_modify_alpha: boolean;
    clear_background: boolean;
    clear_background_color: string;
    background_image: string;
    render_only_selected: boolean;
    live_mode: boolean;
    show_info: boolean;
    allow_dragcanvas: boolean;
    allow_dragnodes: boolean;
    allow_interaction: boolean;
    multi_select: boolean;
    allow_searchbox: boolean;
    allow_reconnect_links: boolean;
    move_destination_link_without_shift: boolean;
    align_to_grid: boolean;
    drag_mode: boolean;
    dragging_rectangle: number[] | null;
    filter: any;
    set_canvas_dirty_on_mouse_event: boolean;
    always_render_background: boolean;
    render_shadows: boolean;
    render_canvas_border: boolean;
    render_connections_shadows: boolean;
    render_connections_border: boolean;
    render_curved_connections: boolean;
    render_connection_arrows: boolean;
    render_collapsed_slots: boolean;
    render_execution_order: boolean;
    render_title_colored: boolean;
    render_link_tooltip: boolean;
    links_render_mode: number;
    mouse: number[];
    graph_mouse: number[];
    canvas_mouse: number[];
    pointer_is_down: boolean;
    pointer_is_double: boolean;
    visible_nodes: LGraphNode[];
    visible_links: any[];
    visible_area: Float32Array;
    node_in_panel: LGraphNode | null;
    node_widget: any;
    over_link_center: any;
    last_mouse_position: number[];
    block_click: boolean;
    last_click_time: number;
    last_click_position: number[];
    visible_area_dirty: boolean;
    dirty_bgcanvas: boolean;
    dirty_canvas: boolean;
    node_dragged: LGraphNode | null;
    node_over: LGraphNode | null;
    node_capturing_input: LGraphNode | null;
    connecting_node: LGraphNode | null;
    highlighted_links: Record<number, boolean>;
    highquality_render: boolean;
    use_gradients: boolean;
    editor_alpha: number;
    pause_rendering: boolean;
    read_only: boolean;
    autoresize: boolean;
    skip_events: boolean;
    selected_nodes: Record<number, LGraphNode>;
    selected_group: LGraphGroup | null;
    selected_group_resizing: boolean;
    dragging_canvas: boolean;
    current_node: LGraphNode | null;
    node_title_color: string;
    default_link_color: string;
    default_connection_color: { input_off: string, input_on: string, output_off: string, output_on: string };
    default_connection_color_byType: Record<string, string>;
    default_connection_color_byTypeOff: Record<string, string>;
    connecting_output: any;
    connecting_input: any;
    connecting_pos: number[] | null;
    connecting_slot: number;
    connecting_links_to: any[];
    dirty_area: number[] | null;
    onMouse: ((event: MouseEvent) => boolean) | null;
    onDrawBackground: ((ctx: CanvasRenderingContext2D, visible_area: Float32Array) => void) | null;
    onDrawForeground: ((ctx: CanvasRenderingContext2D, visible_area: Float32Array) => void) | null;
    onDrawOverlay: ((ctx: CanvasRenderingContext2D) => void) | null;
    onRender: ((canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) => void) | null;
    onDropItem: ((event: DragEvent) => boolean | void) | null;
    onNodeMoved: ((node: LGraphNode) => void) | null;
    onNodeSelected: ((node: LGraphNode) => void) | null;
    onNodeDeselected: ((node: LGraphNode) => void) | null;
    onShowNodePanel: ((node: LGraphNode) => void) | null;
    onNodeDblClicked: ((node: LGraphNode) => void) | null;
    onSelectionChange: ((selection: Record<number, LGraphNode>) => void) | null;
    onSearchBox: ((helper: any, query: string, graphcanvas: LGraphCanvas) => string[]) | null;
    onSearchBoxSelection: ((name: string, event: MouseEvent, graphcanvas: LGraphCanvas) => void) | null;
    onMenuNodeInputs: ((entries: any[]) => any[]) | null;
    onMenuNodeOutputs: ((entries: any[]) => any[]) | null;
    onMenuNodeProperties: ((entries: any[]) => any[]) | null;
    onMenuNodeMode: ((entries: any[]) => any[]) | null;
    onGetNodeMenuOptions: ((options: any[], node: LGraphNode) => any[]) | null;
    onDrawLinkTooltip: ((ctx: CanvasRenderingContext2D, link: any, graphcanvas: LGraphCanvas) => boolean) | null;

    constructor(canvas: HTMLCanvasElement | string, graph?: LGraph, options?: CanvasOptions);

    setCanvas(canvas: HTMLCanvasElement | string, skip_events?: boolean): void;
    setGraph(graph: LGraph | null, skip_clear?: boolean): void;
    getCanvas(): HTMLCanvasElement;
    getCanvasWindow(): Window;
    clear(): void;
    openSubgraph(graph: LGraph): void;
    closeSubgraph(): void;
    getCurrentGraph(): LGraph | null;
    startRendering(): void;
    stopRendering(): void;
    resize(width?: number, height?: number): void;
    setZoom(value: number, zooming_center?: number[]): void;
    bringToFront(node: LGraphNode): void;
    sendToBack(node: LGraphNode): void;
    computeVisibleNodes(nodes?: LGraphNode[], out?: LGraphNode[]): LGraphNode[];
    draw(force_canvas?: boolean, force_bgcanvas?: boolean): void;
    drawFrontCanvas(): void;
    drawBackCanvas(): void;
    drawNode(node: LGraphNode, ctx: CanvasRenderingContext2D): void;
    drawNodeShape(node: LGraphNode, ctx: CanvasRenderingContext2D, size: number[], fgcolor: string, bgcolor: string, selected?: boolean, mouse_over?: boolean): void;
    drawConnections(ctx: CanvasRenderingContext2D): void;
    renderLink(ctx: CanvasRenderingContext2D, a: number[], b: number[], link?: any, skip_border?: boolean, flow?: boolean, color?: string, start_dir?: number, end_dir?: number, num_sublines?: number): void;
    computeConnectionPoint(a: number[], b: number[], t: number, start_dir?: number, end_dir?: number): number[];
    drawExecutionOrder(ctx: CanvasRenderingContext2D): void;
    drawNodeWidgets(node: LGraphNode, posY: number, ctx: CanvasRenderingContext2D, active_widget?: any): number;
    processNodeWidgets(node: LGraphNode, pos: number[], event: any, active_widget?: any): any;
    adjustNodesSize(): void;
    setDirty(foreground?: boolean, background?: boolean): void;
    processMouseDown(e: MouseEvent): boolean | void;
    processMouseMove(e: MouseEvent): boolean | void;
    processMouseUp(e: MouseEvent): boolean | void;
    processMouseWheel(e: WheelEvent): boolean | void;
    processKey(e: KeyboardEvent): boolean | void;
    processDrop(e: DragEvent): boolean | void;
    isOverNodeBox(node: LGraphNode, canvasx: number, canvasy: number): boolean;
    isOverNodeInput(node: LGraphNode, canvasx: number, canvasy: number, slot_pos: number[]): number;
    isOverNodeOutput(node: LGraphNode, canvasx: number, canvasy: number, slot_pos: number[]): number;
    convertOffsetToCanvas(pos: number[], out?: number[]): number[];
    convertCanvasToOffset(pos: number[], out?: number[]): number[];
    convertEventToCanvasOffset(e: MouseEvent): number[];
    getCanvasMenuOptions(): any[];
    getNodeMenuOptions(node: LGraphNode): any[];
    getGroupMenuOptions(group: LGraphGroup): any[];
    showLinkMenu(link: any, e: MouseEvent): boolean;
    createDefaultNodeForSlot(optPass?: any): LGraphNode | null;
    showConnectionMenu(optPass?: any): boolean;
    showSearchBox(event: MouseEvent, options?: any): void;
    showEditPropertyValue(node: LGraphNode, property: string, options?: any): void;
    prompt(title: string, value: any, callback: (v: any) => void, event?: any, multiline?: boolean): any;
    showShowNodePanel(node: LGraphNode): void;
    showSubgraphPropertiesDialog(node: LGraphNode): void;
    showSubgraphPropertiesDialogRight(node: LGraphNode): void;
    checkPanels(): void;
    closePanels(): void;
    centerOnNode(node: LGraphNode): void;
    setZoom(value: number, center?: number[]): void;
    selectNodes(nodes?: LGraphNode[], add_to_current_selection?: boolean): void;
    deselectNode(node: LGraphNode): void;
    deselectAllNodes(): void;
    deleteSelectedNodes(): void;
    copyToClipboard(nodes?: Record<number, LGraphNode>): void;
    pasteFromClipboard(isConnectUnselected?: boolean): void;
    processDrop(e: DragEvent): void;
    bindEvents(): void;
    unbindEvents(): void;
    static active_canvas: LGraphCanvas;
    static onMenuCollapseAll(): void;
    static onMenuNodeEdit(): void;
    static onShowPropertyEditor(item: any, options: any, e: MouseEvent, menu: any, node: LGraphNode): void;
}

export default LGraphCanvas;
